### ISSUE TITLE
Cannot submit answer for questions for Pothole service code

### ISSUE THREAD

**Issue by cagryInside** [CUTR-at-USF/see-click-fix-issues#1]
For the service description, SCF url (http://test.seeclickfix.com/open311/v2/services/989.json?lat=27.847889557881935&long=27.847889557881935) returns the following:

```
{"service_code":989,"attributes":[{"code":"552","required":false,"order":1,"description":"Pinellas County
 monitors SeeClickFix from time to time 8am to 5pm on regular business days for non-emergency 
conditions that are the responsibility of Pinellas County Government. Call 911 for emergencies. 
","datatype_description":null,"variable":false,"datatype":"string","values":null},
{"code":"553","required":false,"order":2,"description":"Is the pothole in the line of traffic or off to the 
side?","datatype_description":null,"variable":true,"datatype":"string","values":null}]}
```

SeeClickFix doesn't show the answer that we submit for the question with `code:553`.

Http POST body:

```
api_key=937033cad3054ec58a1a8156dcdd6ad8a416af2f&service_code=989&service_name=Pothole
&lat=27.87337101888292&long=-82.69908338785172&
address_string=11125+49th+St+N%2C+Clearwater%2C+FL+33762.&description=desc&
first_name=cagri&last_name=usf&email=c1-2-3-4-5%40hotmail.com&device_id=355458060771954&
attribute%5B553%5D=test
```

SeeClickFix Url: http://test.seeclickfix.com/issues/1315306-pothole

**Comment by barbeau** [comment]
SCF's email response:

> Some questions are set to not have their answers displayed on the issue show page, and are only used internally. This is usually done for privacy purposes (e.g if you provide your phone #, it won't display it publicly on the show page). The "Is the pothole in the line of traffic.." question with code 553 for the Pothole service is set to not display the answer. I'm not entirely sure why that one is kept private, but it is something that the partner has chosen. The Open311 spec has no notion of private/public questions, so we're currently not providing an indicator of whether the question is public/private in the response to GET Service. That could be an extra parameter we pass back- something like "answer_is_private": true/false.
